[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
Blosc = "a74b3585-a348-5f62-a45c-50e91977d574"
Cellular = "a5dba43e-3abc-5203-bfc5-584ca68d3f5b"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Dispersal = "72d8b834-28c9-57fc-8b6a-b9450a04c193"
FieldMetadata = "bf96fef3-21d2-5d20-8afa-0e7d4c32a885"
Flatten = "4c728ea3-d9ee-5c9a-9642-b6f7d7dc04fa"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
REPLGamesBase = "061b77f0-9d53-11e8-11f4-7df760718934"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
